<a href="https://colab.research.google.com/github/soumensen411/Machine_Learning_Models_Walkthroughs/blob/main/NLP/Bag_of_words%20%26%20TF-IDF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [140]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [141]:
data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/NLP/train.txt/train.txt',sep=';',header=None,names=['text','emotion'])

In [142]:
data

                                                    text  emotion
0                                i didnt feel humiliated  sadness
1      i can go from feeling so hopeless to so damned...  sadness
2       im grabbing a minute to post i feel greedy wrong    anger
3      i am ever feeling nostalgic about the fireplac...     love
4                                   i am feeling grouchy    anger
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...  sadness
15996  i am now turning and i feel pathetic that i am...  sadness
15997                     i feel strong and good overall      joy
15998  i feel like this was such a rude comment and i...    anger
15999  i know a lot but i feel so stupid because i ca...  sadness

[16000 rows x 2 columns]

In [143]:
data.isnull().sum()

text       0
emotion    0
dtype: int64

In [144]:
unique_emotion = data['emotion'].unique()
emotional_number ={}
i = 0
for emo in unique_emotion:
  emotional_number[emo] = i
  i += 1

In [145]:
data['emotion'] = data['emotion'].map(emotional_number)

In [146]:
data

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

# Convert into lowercase

In [147]:
data['text'] = data['text'].apply(lambda x:x.lower())

In [148]:
data.head(

)

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

# Remove Punctuation

In [149]:
import string
def remove_punctuation(txt):
  return txt.translate(str.maketrans('','',string.punctuation))

In [150]:
data['text'] = data['text'].apply(remove_punctuation)

# Remove Number

In [151]:
def remove_number(txt):
  new = ""
  for i in txt:
    if not i.isdigit():
      new = new+i
  return new
data['text'] = data['text'].apply(remove_number)

In [152]:
data.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

# Removing Emojies

In [153]:
def remove_emojies(txt):
  new = ""
  for i in txt:
    if i.isascii():
      new += i
  return new
data['text'] = data['text'].apply(remove_emojies)

# Remove Stopwords

In [154]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [155]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [156]:
stop_words = stopwords.words('english')
len(stop_words)

198

In [157]:
def remove(txt):
  words = word_tokenize(txt)
  clean_txt = []
  for i in words:
    if not i in stop_words:
      clean_txt.append(i)
  return " ".join(clean_txt)

In [158]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [159]:
data['text'] = data['text'].apply(remove)

In [160]:
data.head()

                                                text  emotion
0                              didnt feel humiliated        0
1  go feeling hopeless damned hopeful around some...        0
2          im grabbing minute post feel greedy wrong        1
3  ever feeling nostalgic fireplace know still pr...        2
4                                    feeling grouchy        1

In [161]:
X = data['text']
y = data['emotion']

In [162]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [163]:
data.shape

(16000, 2)

In [164]:
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer

In [165]:
bow_vectorization = CountVectorizer()

In [179]:
X_train_bow = bow_vectorization.fit_transform(X_train)
X_test_bow = bow_vectorization.transform(X_test)

In [167]:
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()

In [168]:
nb.fit(X_train_bow,y_train)

MultinomialNB()

In [169]:
from sklearn.metrics import accuracy_score

y_pred_bow = nb.predict(X_test_bow)
accuracy_bow = accuracy_score(y_test, y_pred_bow)
print(f"Accuracy Score (Bag-of-Words): {accuracy_bow:.4f}")

Accuracy Score (Bag-of-Words): 0.7678

In [170]:
Tfidf_vectorizer = TfidfVectorizer()

In [180]:
X_train_tfidf = Tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = Tfidf_vectorizer.transform(X_test)

In [176]:
nb_tfidf = MultinomialNB()
nb_tfidf.fit(X_train_tfidf,y_train)

MultinomialNB()

In [181]:
y_pred_tfidf = nb_tfidf.predict(X_test_tfidf)

In [178]:
accuracy_tfidf = accuracy_score(y_test, y_pred_tfidf)
print(f"Accuracy Score (Bag-of-Words): {accuracy_tfidf:.4f}")

Accuracy Score (Bag-of-Words): 0.6609

In [182]:
from sklearn.linear_model import LogisticRegression
log_reg_bow = LogisticRegression(max_iter=1000)
log_reg_bow.fit(X_train_bow, y_train)

LogisticRegression(max_iter=1000)

In [183]:
y_pred_log_reg_bow = log_reg_bow.predict(X_test_bow)
accuracy_log_reg_bow = accuracy_score(y_test, y_pred_log_reg_bow)
print(f"Accuracy Score (Logistic Regression with Bag-of-Words): {accuracy_log_reg_bow:.4f}")

Accuracy Score (Logistic Regression with Bag-of-Words): 0.8888

Let's also try Logistic Regression with TF-IDF features.

In [184]:
log_reg_tfidf = LogisticRegression(max_iter=1000)
log_reg_tfidf.fit(X_train_tfidf, y_train)

LogisticRegression(max_iter=1000)

In [185]:
y_pred_log_reg_tfidf = log_reg_tfidf.predict(X_test_tfidf)

accuracy_log_reg_tfidf = accuracy_score(y_test, y_pred_log_reg_tfidf)
print(f"Accuracy Score (Logistic Regression with TF-IDF): {accuracy_log_reg_tfidf:.4f}")

Accuracy Score (Logistic Regression with TF-IDF): 0.8616