<a href="https://colab.research.google.com/github/soumensen411/Machine_Learning_Models_Walkthroughs/blob/main/NLP/test_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [40]:
data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/NLP/train.txt/train.txt',sep=';',header=None,names=['text','emotion'])

In [41]:
data

                                                    text  emotion
0                                i didnt feel humiliated  sadness
1      i can go from feeling so hopeless to so damned...  sadness
2       im grabbing a minute to post i feel greedy wrong    anger
3      i am ever feeling nostalgic about the fireplac...     love
4                                   i am feeling grouchy    anger
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...  sadness
15996  i am now turning and i feel pathetic that i am...  sadness
15997                     i feel strong and good overall      joy
15998  i feel like this was such a rude comment and i...    anger
15999  i know a lot but i feel so stupid because i ca...  sadness

[16000 rows x 2 columns]

In [42]:
data.isnull().sum()

text       0
emotion    0
dtype: int64

In [43]:
unique_emotion = data['emotion'].unique()
emotional_number ={}
i = 0
for emo in unique_emotion:
  emotional_number[emo] = i
  i += 1

In [44]:
data['emotion'] = data['emotion'].map(emotional_number)

In [45]:
data

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

# Convert into lowercase

In [47]:
data['text'] = data['text'].apply(lambda x:x.lower())

In [48]:
data.head(

)

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

# Remove Punctuation

In [51]:
import string
def remove_punctuation(txt):
  return txt.translate(str.maketrans('','',string.punctuation))

In [52]:
data['text'] = data['text'].apply(remove_punctuation)

# Remove Number

In [53]:
def remove_number(txt):
  new = ""
  for i in txt:
    if not i.isdigit():
      new = new+i
  return new
data['text'] = data['text'].apply(remove_number)

In [54]:
data.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

# Removing Emojies

In [55]:
def remove_emojies(txt):
  new = ""
  for i in txt:
    if i.isascii():
      new += i
  return new
data['text'] = data['text'].apply(remove_emojies)

# Remove Stopwords

In [59]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [60]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [66]:
stop_words = stopwords.words('english')
len(stop_words)

198

In [69]:
def remove(txt):
  words = word_tokenize(txt)
  clean_txt = []
  for i in words:
    if not i in stop_words:
      clean_txt.append(i)
  return " ".join(clean_txt)

In [71]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [72]:
data['text'] = data['text'].apply(remove)

In [73]:
data.head()

                                                text  emotion
0                              didnt feel humiliated        0
1  go feeling hopeless damned hopeful around some...        0
2          im grabbing minute post feel greedy wrong        1
3  ever feeling nostalgic fireplace know still pr...        2
4                                    feeling grouchy        1